# Generated by Django 4.2.3 on 2023-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(default='DALLE_2023-02-06_11.01.43_-_a_guy_coding_wearing_a_hoddie_and_glasses_digital_art.png', upload_to='images'),
        ),
    ]
