# Generated by Django 4.2.3 on 2023-07-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(default='pereanu-sebastian-qFH7-yKoxik-unsplash.jpg', upload_to='images'),
        ),
    ]
